version: '2'


services:
  sparkweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sparkweb
    ports:
      - "34000:6000"
  sparkweb2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sparkweb2
    ports:
      - "34001:6000"
  sparkweb3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sparkweb3
    ports:
      - "34002:6000"
#  sparklog:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: sparklog
#    ports:
#      - "35000:7000"

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: